os:
  - linux
  - osx
  - windows
language: rust
rust:
  - 1.33.0
  - stable
  - beta
  - nightly
before_script:
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then rustup component add rustfmt clippy; fi
script:
  - cargo build
  - cargo test --all
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then cargo fmt -all -- --check; fi
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then cargo clippy -- -D warnings; fi

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
