language: rust
rust:
  - 1.33.0
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - rustup component add rustfmt clippy
script:
  - cargo build
  - cargo test
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
