[package]
name = "gumpi"
version = "0.1.0"
authors = ["Marcin Mielniczuk <marmistrz.dev@zoho.eu>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
serde_json = "1.0"
serde = "1.0"
failure = "0.1"
log = "0.4"
env_logger = "0.6"
structopt = "0.2"
dirs = "1.0"
serde_derive = "1.0"
toml = "0.4.8"
