[package]
name = "gumpi"
version = "0.1.0"
authors = ["Marcin Mielniczuk <marmistrz.dev@zoho.eu>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
serde_json = "1.0"
serde = "1.0"
failure = "0.1"
log = "0.4"
env_logger = "0.6"
structopt = "0.2"
dirs = "1.0"
serde_derive = "1.0"
toml = "0.4.8"
gu-net = { git = "https://github.com/golemfactory/golem-unlimited" }
gu-model = { git = "https://github.com/golemfactory/golem-unlimited" }
gu-client = { git = "https://github.com/golemfactory/golem-unlimited", branch = "gu-client"}
tokio = "0.1.14"
futures = "0.1.25"
actix-web = { git = "https://github.com/marmistrz/actix-web" }
actix = "0.7.9"
tokio-signal = "0.2.7"
