[package]
authors = ["Marcin Mielniczuk <marmistrz.dev@zoho.eu>"]
edition = "2018"
name = "gumpi"
version = "0.1.0"

[features]
# Enabling this feature will prevent the sessions from being closed on exit.
# As a consequence, ctrl-c will no longer kill the job on the provider node
# if the feature is enabled.
# This feature is intended only for debugging purposes.
noclean_session = []

[dependencies]
actix = "0.7.9"
bytes = "0.4.12"
dirs = "1.0"
env_logger = "0.6"
failure = "0.1"
futures = "0.1.25"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
tokio = "0.1.14"
tokio-signal = "0.2.7"
toml = "0.4.8"

[dependencies.actix-web]
git = "https://github.com/marmistrz/actix-web"

[dependencies.gu-model]
branch = "gumpi-freeze"
git = "https://github.com/golemfactory/golem-unlimited"

[dependencies.gu-net]
branch = "gumpi-freeze"
git = "https://github.com/golemfactory/golem-unlimited"
