[package]
authors = ["Marcin Mielniczuk <marmistrz.dev@zoho.eu>"]
edition = "2018"
name = "gumpi"
version = "0.1.0"
[dependencies]
actix = "0.7.9"
bytes = "*"
dirs = "1.0"
env_logger = "0.6"
failure = "0.1"
futures = "0.1.25"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
tokio = "0.1.14"
tokio-signal = "0.2.7"
toml = "0.4.8"

[dependencies.actix-web]
git = "https://github.com/marmistrz/actix-web"

[dependencies.gu-model]
branch = "gumpi-ethsign"
git = "https://github.com/golemfactory/golem-unlimited"

[dependencies.gu-net]
branch = "gumpi-ethsign"
git = "https://github.com/golemfactory/golem-unlimited"
